'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('fs'),path=require('path'),os=require('os'),{execFileSync}=require('child_process');
const {runProject}=require('../dist/services/project-service');
test('PB8 builds an x86 EXE/PBD with a Chinese relative PBR resource', {skip:process.platform!=='win32'},()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'pb-native-'));
 try{
  const base=path.join(root,'中文工程');fs.mkdirSync(base);
  const cli=path.resolve(__dirname,'../pb-native-host.exe'),pbl=path.join(base,'smoke.pbl');
  const call=args=>execFileSync(cli,['--version=80',...args],{encoding:'utf8',windowsHide:true});
  call(['create-pbl',pbl]);
  const source=['$PBExportHeader$smoke.sra','forward','global type smoke from application','end type','end forward','global type smoke from application','string appname = "smoke"','end type','global smoke smoke','on smoke.create','end on','on smoke.destroy','end on',''].join('\r\n');
  const sra=path.join(base,'smoke.sra');
  const globals=['global transaction sqlca','global dynamicdescriptionarea sqlda','global dynamicstagingarea sqlsa','global error error','global message message'].join('\r\n');
  const create=['sqlca = create transaction','sqlda = create dynamicdescriptionarea','sqlsa = create dynamicstagingarea','error = create error','message = create message'].join('\r\n');
  const destroy=['destroy(sqlca)','destroy(sqlda)','destroy(sqlsa)','destroy(error)','destroy(message)'].join('\r\n');
  const runnable=source.replace('end forward',globals+'\r\nend forward').replace('on smoke.create\r\n','on smoke.create\r\n'+create+'\r\n').replace('on smoke.destroy\r\n','on smoke.destroy\r\n'+destroy+'\r\n');
  fs.writeFileSync(sra,runnable+'event open;\r\ninteger li_file\r\nli_file = FileOpen("native-smoke.txt", LineMode!, Write!, LockWrite!, Replace!)\r\nif li_file > 0 then\r\nFileWrite(li_file, "native-ok")\r\nFileClose(li_file)\r\nend if\r\nend event\r\n','utf8');call(['import',pbl,sra,'smoke']);
  fs.writeFileSync(path.join(base,'smoke.pbt'),'appname "smoke";\napplib "smoke.pbl";\nliblist "smoke.pbl";\n','utf8');
  const bmp=Buffer.alloc(58);bmp.write('BM');bmp.writeUInt32LE(58,2);bmp.writeUInt32LE(54,10);bmp.writeUInt32LE(40,14);bmp.writeInt32LE(1,18);bmp.writeInt32LE(1,22);bmp.writeUInt16LE(1,26);bmp.writeUInt16LE(24,28);bmp.writeUInt32LE(4,34);bmp[56]=255;
  fs.mkdirSync(path.join(base,'res'));fs.writeFileSync(path.join(base,'res','资源图.bmp'),bmp);
  fs.writeFileSync(path.join(base,'smoke.pbr'),'res\\资源图.bmp\r\n','utf8');
  const outDir=path.join(root,'输出目录');fs.mkdirSync(outDir);
  const result=runProject(path.join(base,'smoke.pbt'),80,{runRoot:path.join(root,'logs'),traceObjects:true,exePath:path.join(outDir,'smoke.exe')},'build');
  const events=fs.readFileSync(path.join(result.runDir,'progress.jsonl'),'utf8').trim().split(/\r?\n/).map(JSON.parse);
  assert.ok(events.some(e=>e.objectEvent==='progress'&&e.name==='smoke.sra'));
  assert.ok(events.some(e=>e.objectEvent==='writing'&&e.name==='smoke.apl'), 'Native writer must report the application object');
  assert.ok(events.filter(e=>e.objectEvent==='writing').every(e=>e.library.toLowerCase()===pbl.toLowerCase()));
  assert.equal(events.filter(e=>e.stage==='full-rebuild').length,1);
  assert.equal(events.some(e=>e.stage==='trace-objects'),false);
  assert.equal(result.success,true,JSON.stringify(result));assert.equal(result.errors.length,0);assert.equal(result.artifacts.length,2);
  assert.ok(fs.existsSync(path.join(base,'smoke.pbd')));
  assert.equal(fs.existsSync(path.join(outDir,'smoke.pbd')),false);
  const release=path.join(root,'发布','bin');
  const copied=runProject(path.join(base,'smoke.pbt'),80,{runRoot:path.join(root,'logs'),exePath:path.join(outDir,'smoke.exe'),outputDir:release},'build');
  assert.equal(copied.success,true,JSON.stringify(copied));
  assert.equal(copied.copiedArtifacts.length,2);
  assert.deepEqual(fs.readFileSync(path.join(base,'smoke.pbd')),fs.readFileSync(path.join(release,'smoke.pbd')));
  assert.deepEqual(fs.readFileSync(path.join(outDir,'smoke.exe')),fs.readFileSync(path.join(release,'smoke.exe')));
  const runtime=JSON.parse(call(['info',pbl])).runtimeDir;
  execFileSync(path.join(release,'smoke.exe'),[],{cwd:release,timeout:10000,windowsHide:true,env:{...process.env,PATH:runtime+';'+process.env.PATH}});
  assert.match(fs.readFileSync(path.join(release,'native-smoke.txt'),'utf8'),/native-ok/);
  const embedded=runProject(path.join(base,'smoke.pbt'),80,{runRoot:path.join(root,'logs'),exePath:path.join(outDir,'embedded.exe'),pbdFlags:[0]},'build');
  assert.equal(embedded.success,true,JSON.stringify(embedded));
  const embeddedEvents=fs.readFileSync(path.join(embedded.runDir,'progress.jsonl'),'utf8').trim().split(/\r?\n/).map(JSON.parse);
  assert.ok(embeddedEvents.some(e=>e.objectEvent==='writing'&&e.name==='smoke.apl'),'EXE writer must report embedded objects');
  assert.equal(embeddedEvents.some(e=>e.stage&&e.stage.startsWith('create-pbd:')),false);
  execFileSync(embedded.exePath,[],{cwd:outDir,timeout:10000,windowsHide:true,env:{...process.env,PATH:runtime+';'+process.env.PATH}});
  assert.match(fs.readFileSync(path.join(outDir,'native-smoke.txt'),'utf8'),/native-ok/);
  const exe=fs.readFileSync(result.exePath),pe=exe.readUInt32LE(60);assert.equal(exe.readUInt16LE(pe+4),0x14c);assert.ok(exe.includes(Buffer.from('PBVM80.dll')));
  assert.equal(fs.readdirSync(base).some(x=>x.startsWith('.pb-ai-resources-')),false);
 }finally{fs.rmSync(root,{recursive:true,force:true});}
});

